# Generated by Django 5.2.6 on 2025-09-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
